Module4 task1
htmlacademy-javascript/1236243-kekstagram-simple-27 pull request #3
Opened 2022-10-15 20:23 UTC by Iakovlev-Dev

2022-10-20 12:18 UTC, nlold requested changes
Необходимы небольшие изменения

2022-10-20 12:18 UTC, nlold commented on js/main.js
> +  if(typeof comment === 'string') {
Вот тут лучше сделать так

```
if (typeof comment === 'string' && comment.length <= maxLength) {
return true
} 

return false;
```

2022-10-20 12:18 UTC, nlold commented on js/main.js
> +  for (let i = 1; i <= 25; i++) {
В целом, это рабочий вариант, но будет круто, если сделаешь именно генерирование ID внутри этого массива, чтобы сделать максимально разнородные данные, а не просто текущую позицию элемента.

2022-10-20 14:11 UTC, Iakovlev-Dev commented on js/main.js
> +  for (let i = 1; i <= 25; i++) {
Я вначале использовал array.from, но у меня почему то не появлялся массив. Просмотрев внимательно, я исправил ошибку: const getFotos = () => **{**Array.from({ length: FOTOS }, (_, index) => createDescriptionFoto(index + 1))**}**;
ставил тут кавычки

2022-10-21 11:58 UTC, nlold commented on js/main.js
> +const getFotos = () => Array.from({ length: FOTOS }, (_, index) => createDescriptionFoto(index + 1));
По сути же ничего не изменилось)

Под случайной генерацией я имел в виду следующий алгоритм:

1) Запускается цикл
2) Внутри цикла генерируется рандомный ID для фото
3) Объект с информацией о фото добавляется в массив
4) Если цикл не закончился, возвращаемся к пункту 1, а если закончился, то выходим из массива

И для этого кейса, также необходимо учитывать, чтобы сгенерированные ID не повторялись.

2022-10-24 10:04 UTC, nlold approved these changes

2022-10-24 10:04 UTC, merged